### ISSUE TITLE
End region corruption after processing

### ISSUE THREAD

**Issue by TptMike** [Everneth/NetworkScripts#2]
When the script is run manually, the end region files are processed cleanly and the end is reset properly. When the script is run via crontab, the end region files are processed but corrupted in the process.

## Todo
- [ ] Determine the cause of corruption
- [ ] See if the python script can be offloaded to another means, ie: java or bash
- [ ] Implement fix
- [ ] Test with copy of S5 world on Build
